### ISSUE TITLE
Named/reserved lobbies are displayed in number form when outside the lobby menu

### ISSUE THREAD

**Issue by MatthewRobo** [shiburizu/concerto-mbaacc#11]
![image](https://user-images.githubusercontent.com/12466011/131590740-6806fffa-d0d6-4104-8e10-99f45894dc90.png)
![image](https://user-images.githubusercontent.com/12466011/131590728-e72711ae-b22d-4c02-a6c2-67f96bef86d5.png)

When still connected to a lobby, named lobbies are not displayed in named form in the top bar while in the Main Menu.

**Comment by shiburizu** [comment]
This is not a bug. The server uses a 4-digit code for all lobbies including aliased lobbies.

In the future this may change however since both identifiers are valid ways to connect to a lobby it isn't an issue.
