### ISSUE TITLE
Direct Match Does not Work

### ISSUE THREAD

**Issue by Robonics** [shiburizu/concerto-mbaacc#14]
System: Windows 10

Attempting to connect to another user directly (who was using cccaster) resulted in not being able to start the match. The ping sound effect played when they connected but the game did not start and the modal showed no changes. My only guess is that cccaster expects to be given a rollback and delay value like it does when you do netplay directly through the caster.

**Comment by shiburizu** [comment]
Concerto creates a "concerto-logs" folder for text files as a written history of CCCaster netplay attempts. Please provide me with the log file relevant to your netplay session in order for me to review the output and find the issue.
